spring.application.name=auth-service
# Server Port
server.port=8082

# OAuth2 Authorization Server
auth.admin-service.base-url=http://localhost:8081
auth.issuer=http://localhost:8082
auth.token.expiry=3600
auth.token.refresh-expiry=7200

# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always