spring.application.name=subscription-service
# Server Port
server.port=8085

# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://localhost:5432/subscription_db
spring.datasource.username=postgres
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Basic Security (temporary)
spring.security.user.name=admin
spring.security.user.password=admin

# Actuator
management.endpoints.web.exposure.include=*